Feature/nsup 32/redirect after passing test
oat-sa/extension-tao-ltideliveryprovider pull request #277
Opened 2020-10-08 10:31 UTC by AndreyNegrov

**Related to task:**  https://oat-sa.atlassian.net/browse/NSUP-32
**Description:** TAO randomly not redirecting to postbackURL after test completion
**How to test:**  
1. pass test through LTI. 
2. run the test again
After that you will be redirected to the 'Return URL' page

2020-10-29 14:41 UTC, tikhanovichA approved these changes
**Review Checklist**
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-10-29 15:58 UTC, augustas requested changes
Works on my machine, a few changes suggested.

2020-10-29 15:58 UTC, augustas commented on controller/DeliveryTool.php
> +    const FORCE_REDIRECT_TO_RETURN_URL = 'custom_force_redirect_to_return_url';
It seems that the convention for constants are `PARAM_*`. And the name of parameter seems misleading for me, it does not force much, f.e. if test taker never started the delivery then there is no redirect. I'd suggest `PARAM_SKIP_OVERVIEW`

2020-10-29 15:58 UTC, augustas commented on controller/DeliveryTool.php
> +            $url = _url(
I think it would be better to use the `LtiNavigationService::getReturnUrl(...)` to build the return url

2020-10-30 10:30 UTC, augustas approved these changes
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-10-30 10:31 UTC, merged