Feature/tr 1867/launch test with lti 1p3
oat-sa/extension-tao-ltideliveryprovider pull request #290
Opened 2021-09-16 08:03 UTC by emgolubev

Related to: https://oat-sa.atlassian.net/browse/TR-1867

2021-09-21 14:57 UTC, wazelin commented on controller/DeliveryTool.php
> +        LtiService::singleton()->startLti1p3Session($message);
Don't forget to update `composer.json` with a new version of `extension-tao-lti`, implementing that method.
Feel free to specify the `dev-*` version there so far, just as a placeholder, not to forget bumping the requirement before the merge.

2021-09-21 15:03 UTC, wazelin requested changes

2021-09-22 22:11 UTC, alexeyvy approved these changes
- [ ] New code is covered by tests (if applicable) - not applicable, as the changes are places in controllers/migration/manigest - therefore, not testable in terms of cgen
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-09-23 09:25 UTC, wazelin requested changes
I can see a few empty files here.
Also, the file permissions seem to have changed for some reason.

![image](https://user-images.githubusercontent.com/2943256/134483956-13f23cba-c12d-41df-9e90-0583810b7e5d.png)

2021-09-23 12:05 UTC, wazelin approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2021-09-23 12:06 UTC, wazelin commented
Please merge only after the taoLti extension has been released by the automated GitHub action.

2021-09-24 09:00 UTC, merged