fix: Showing "Attempts limits has reached" message when taking a test in TT portal if Max. Executions value is given as empty for TAO Enterprise INVALSI PHP 8.1
oat-sa/extension-tao-ltideliveryprovider pull request #331
Opened 2023-04-04 12:56 UTC by jeethufoc

Related to https://oat-sa.atlassian.net/browse/INV-639

Description: 

when trying to take a test in Test-taker portal using the user created during the  remote publishing getting message  “Attempts limits has reached” and not able to take the test.  
We have  given Max. Executions(default: unlimited) = ''  in Tao application delivery tab

![Delivery_Tab1](https://user-images.githubusercontent.com/74544631/229798018-146195cf-7b5a-43e9-942b-b524f525ab84.png)

2023-04-04 13:24 UTC, bartlomiejmarszal requested changes
Please do not use client details (screenshots, name) in openspource repositories. 
Is there a test for this class? 

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2023-04-04 14:02 UTC, jeethufoc commented
1. Please do not use client details (screenshots, name) in openspource repositories. - Removed 
2 . Is there a test for this class?  - yes(test/unit/model/LtiAssignmentTest.php)

2023-04-06 11:42 UTC, bartlomiejmarszal approved these changes

2023-04-10 19:49 UTC, uncleempty approved these changes
LGTM

2023-04-11 10:29 UTC, merged