fix: pass proper grading status during ags recalculate
oat-sa/extension-tao-ltideliveryprovider pull request #334
Opened 2023-04-20 15:23 UTC by Karol-Stelmaczonek

Ticket: https://oat-sa.atlassian.net/browse/INF-183

## What's Changed

- Fixed change of gradingProgress during AGS call

## Dependencies PRs

- https://github.com/oat-sa/extension-tao-outcome/pull/242

## How to test
-Create a test with an item with the SCORE variable manually graded.
-Take the test. The item should have SCORE = 0.
-Hit the API in TR-4956 with send_ags parameter set to true and no request body.
- Check the payload of the AGS notification.

2023-04-21 10:01 UTC, andreluizmachado requested changes
Is it possible to add unit tests?

2023-04-21 13:25 UTC, pnal approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2023-04-21 13:25 UTC, pnal commented on model/events/LtiAgsListener.php
> +                'timestamp' => time(),
Could you confirm this with Julien, is it ok to send timestamp of moment when we send it instead of e.g. moment when API has been called?

2023-04-25 08:27 UTC, pnal approved these changes

2023-04-25 08:27 UTC, pnal commented on model/events/LtiAgsListener.php
> +        ?string $gradingTimestamp = null
```suggestion
        string $timestamp = (string) time()
```

2023-04-25 08:27 UTC, pnal commented on model/events/LtiAgsListener.php
> +            $taskBody['data']['timestamp'] = $gradingTimestamp;
remove

2023-04-25 08:27 UTC, pnal commented on model/events/LtiAgsListener.php
>                  'scoreMaximum' => $scoreTotalMax,
```suggestion
                'scoreMaximum' => $scoreTotalMax,
                'timestamp' => $timestamp,
```

2023-04-25 09:49 UTC, bartlomiejmarszal reviewed
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2023-04-25 09:58 UTC, bartlomiejmarszal approved these changes

2023-05-11 09:27 UTC, merged